---
- name: Provision the server
  hosts: all
  become: yes

  tasks:
    - name: Update the system
      apt:
        update_cache: yes

    - name: Install Python and MySQL dependencies
      apt:
        name:
          - python3
          - python3-pip
          - mysql-server
          - python3-dev
          - default-libmysqlclient-dev
          - build-essential
        state: present

    - name: Install Python MySQL client
      pip:
        name: mysqlclient

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: your_root_password
        host: localhost
        state: present

    - name: Create a new MySQL user
      mysql_user:
        name: "{{ lookup('env', 'DB_USER') }}"
        password: "{{ lookup('env', 'DB_PASSWORD') }}"
        host: localhost
        state: present

    - name: Create database and load initial data
      mysql_db:
        name: universidad
        state: present

    - name: Load initial data from SQL file
      mysql_db:
        name: universidad
        state: import
        target: /vagrant/init_data.sql

    - name: Copy .env file
      copy:
        src: /vagrant/app/.env
        dest: /home/vagrant/app/.env
